version: "3.7"

x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - rhombus-net

x-backend:
    &backend
    <<: *defaults
    build:
        context: .
        dockerfile: ./apps/backend/dev.Dockerfile
    restart: always
    environment:
        APP_ROOT_PASSWORD: password
        APP_MINIO_SERVER_HOST: storage
        APP_MINIO_SERVER_ACCESS_KEY: minio
        APP_MINIO_SERVER_ACCESS_SECRET_KEY: miniosecret
        APP_BROKER_HOST: task-broker
        APP_BROKER_USER: rhombus
        APP_BROKER_PASSWORD: password
        APP_BUCKET_NAME: rhombus
    volumes:
        - ./apps/backend:/app

services:
  backend:
    <<: *backend
    command: scripts/run_dev_server.sh
    ports:
      - "2222:22"
    depends_on:
      - db
      - storage
  workers:
    <<: *backend
    command: scripts/run_workers.sh
    depends_on:
      - db
      - storage
      - backend
  web:
    <<: *defaults
    command: pnpm --filter web dev
    restart: always
    build:
      args:
        APP: web
        START_COMMAND: dev
      context: .
      dockerfile: apps/web/dev.Dockerfile
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    depends_on:
      - storage
      - backend
  db:
    <<: *defaults
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  storage:
    <<: *defaults
    image: bitnami/minio
    ports:
      - "19000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
      MINIO_DEFAULT_BUCKETS: rhombus
    volumes:
      - storage-data:/data
  storage-configure:
    <<: *defaults
    build:
        context: ./configs
        dockerfile: ./mc.Dockerfile
    environment:
      MINIO_SERVER_HOST: storage
      MINIO_SERVER_ACCESS_KEY: minio
      MINIO_SERVER_ACCESS_SECRET_KEY: miniosecret
      WEBHOOK_URL: http://backend:8000/webhooks/minio/
    depends_on:
      - storage
  gateway:
    <<: *defaults
    image: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
        - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - backend
      - storage
      - sse-stream
  sse-stream:
    <<: *defaults
    image: fanout/pushpin
    restart: always
    volumes:
      - ./configs/routes:/etc/pushpin/routes
  task-broker:
    <<: *defaults
    image: bitnami/rabbitmq
    restart: always
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
      - ./configs/rabbitmq.conf:/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
networks:
  rhombus-net:
    driver: bridge

volumes:
  db-data:
  storage-data:
  rabbitmq_data:

