# Generated by Django 5.0.3 on 2024-04-01 14:27

import django_ulid.models
import inferstate.state_machine
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infersession',
            name='state',
            field=models.CharField(choices=[('init', 'INIT'), ('generate_presigned_url', 'GENERATE_PRESIGNED_URL'), ('file_uploaded', 'FILE_UPLOADED'), ('validate_file', 'VALIDATE_FILE'), ('infer_file', 'INFER_FILE'), ('success', 'SUCCESS'), ('error', 'ERROR')], default=inferstate.state_machine.States['INIT'], max_length=255),
        ),
    ]
